-- Seed jemaat from: Data Jemaat Gereja AMIN Jemaat Tangerang Raya (1).xlsx
-- Generated from Excel sheet `Database`.
-- Source rows: 174 individuals, 55 families, 4 sectors.
-- Safe to run more than once: uses upsert by sectors.name, families.no_kk, individuals.no_induk.
-- This file only seeds jemaat data. It does not modify auth users/profiles.

begin;

with incoming_sectors(name) as (
  values
    ('Anugerah'),
    ('Betlehem'),
    ('Eben-Haezer'),
    ('Nazaret')
)
insert into public.sectors (name, is_active)
select name, true
from incoming_sectors
where name is not null
on conflict (name) do update
set is_active = true,
    updated_at = now();

with incoming_families(no_kk, nama_kepala_keluarga, pasangan, sector_name, status) as (
  values
    ('TGR001', 'Alfa Nituju Ekadiputra Hia', 'Yemima Daeli', 'Eben-Haezer', 'Aktif'),
    ('TGR002', 'Salema Daeli', 'Salema Daeli', 'Eben-Haezer', 'Aktif'),
    ('TGR003', 'Hadali Daeli', 'Fatiria Daeli', 'Eben-Haezer', 'Aktif'),
    ('TGR004', 'Yosia Halawa', null, 'Eben-Haezer', 'Aktif'),
    ('TGR005', 'Estomi Laia', 'Irena Jeska Barasi Gaho', 'Nazaret', 'Aktif'),
    ('TGR006', 'Sumardin Hura', 'Tutry Agus Delina Zega', 'Nazaret', 'Aktif'),
    ('TGR007', 'Arifman Jaya Hura', 'Ike Trajelita Nurjana Harefa', 'Nazaret', 'Aktif'),
    ('TGR008', 'Tomi Laia', 'Lies Susanti Duha', 'Eben-Haezer', 'Aktif'),
    ('TGR009', 'Yohan Sosana Harefa', 'Herlina', 'Eben-Haezer', 'Aktif'),
    ('TGR010', 'Asaziduhu Ndruru', 'Herlina', 'Eben-Haezer', 'Aktif'),
    ('TGR011', 'Agustinus Halawa', 'Metilia Tafonao', 'Eben-Haezer', 'Aktif'),
    ('TGR012', 'Deali Halawa', 'Elly Dwi Utami', 'Eben-Haezer', 'Aktif'),
    ('TGR013', 'Kasia Zebua', 'Kasia Zebua', 'Eben-Haezer', 'Aktif'),
    ('TGR015', 'Montanus Buulolo', 'Wenima Waruwu', 'Eben-Haezer', 'Aktif'),
    ('TGR016', 'Kecitaan Harefa', 'Kariani Harefa', 'Nazaret', 'Aktif'),
    ('TGR017', 'Arojasa Harefa', null, 'Betlehem', 'Aktif'),
    ('TGR018', 'Viktor Zalukhu', null, 'Nazaret', 'Aktif'),
    ('TGR019', 'Adrianus Mendrofa', 'Niat Mawati Fakho', 'Anugerah', 'Aktif'),
    ('TGR020', 'Agustinus Ndruru', 'T Nurmawati Mendrofa', 'Anugerah', 'Aktif'),
    ('TGR021', 'Sisudin Waruwu', 'Sri Kurnia', 'Anugerah', 'Aktif'),
    ('TGR022', 'Beniyami Gea', 'Eva Sandra Indah Hia', 'Anugerah', 'Aktif'),
    ('TGR023', 'Alinur Zebua', 'Tiena Daeli', 'Anugerah', 'Aktif'),
    ('TGR024', 'Juan Edra Agung Zebua', 'Novita Sari Zandroto', 'Anugerah', 'Aktif'),
    ('TGR025', 'Bahagia Halawa', 'Rosliani Buulolo', 'Nazaret', 'Aktif'),
    ('TGR026', 'Remis Putra Tafonao', null, 'Nazaret', 'Aktif'),
    ('TGR027', 'Desman Berkati Larosa', 'Sumiaty Aiba', 'Anugerah', 'Aktif'),
    ('TGR028', 'Simei Waruwu', 'Yaniwati Telaumbanua', 'Anugerah', 'Aktif'),
    ('TGR029', 'Iman Wahyudi Zega', 'Jeni Muliani Gea', 'Nazaret', 'Aktif'),
    ('TGR030', 'Rahmat Jeni Putra Hia', 'Mitra Fianti Daeli', 'Anugerah', 'Aktif'),
    ('TGR031', 'Aperius Zai', 'Etilia Gulo', 'Nazaret', 'Aktif'),
    ('TGR032', 'Tema Putra Telaumbanua', null, 'Anugerah', 'Aktif'),
    ('TGR033', 'Meylvan Putri Jelita Gulo', null, 'Anugerah', 'Aktif'),
    ('TGR034', 'Yustinus Hura', null, 'Eben-Haezer', 'Aktif'),
    ('TGR035', 'Hendrika Frans Telaumbanua', null, 'Anugerah', 'Aktif'),
    ('TGR036', 'Mareti Waruwu', 'Agustina Ovilia Putri', 'Betlehem', 'Aktif'),
    ('TGR037', 'Julisman Gea', 'Ernayanti Telaumbanua', 'Betlehem', 'Aktif'),
    ('TGR038', 'Viktor Iman Jaya Laowo', 'Milika Daeli', 'Betlehem', 'Aktif'),
    ('TGR039', 'Samelia Waruwu', 'Samelia Waruwu', 'Eben-Haezer', 'Aktif'),
    ('TGR040', 'Gregorius Firdaus Riski Gulo', 'Meriani Gulo', 'Betlehem', 'Aktif'),
    ('TGR041', 'Oktafpianus Gea', 'Satima Daeli', 'Betlehem', 'Aktif'),
    ('TGR042', 'Serianus Waruwu', null, 'Betlehem', 'Aktif'),
    ('TGR043', 'Purnama Larosa', 'Tiurlina Telaumbanua', 'Betlehem', 'Aktif'),
    ('TGR044', 'Linus Levis Gulo', 'Sumiati Tafonao', 'Betlehem', 'Aktif'),
    ('TGR045', 'Arius Harefa', 'Nani', 'Nazaret', 'Aktif'),
    ('TGR046', 'Fransiskus Ferdiniato Gulo', 'Jernih Putri Harefa', 'Betlehem', 'Aktif'),
    ('TGR047', 'Juliman Agus Ndruru', 'Aleksi Lilis Arlina Gulo', 'Betlehem', 'Aktif'),
    ('TGR048', 'Yusman Gumanõ', 'Satilia La''ia', 'Betlehem', 'Aktif'),
    ('TGR049', 'Fazokhi Waruwu', null, 'Nazaret', 'Aktif'),
    ('TGR050', 'Temi Candra', null, 'Betlehem', 'Aktif'),
    ('TGR051', 'March Dalta Jonathan Halawa', null, 'Nazaret', 'Aktif'),
    ('TGR052', 'Yupiter Daeli', 'Eltariat Sihura', 'Betlehem', 'Aktif'),
    ('TGR053', 'Sonasa Zendrato', null, 'Anugerah', 'Aktif'),
    ('TGR054', 'Desman Larosa', 'Wenisia Gea', 'Betlehem', 'Aktif'),
    ('TGR055', 'Noferius Telaumbanua', 'Wahyufin Laia', 'Betlehem', 'Aktif'),
    ('TGR056', 'Salman Rion Giawa', null, 'Nazaret', 'Aktif')
)
insert into public.families (
  no_kk,
  nama_kepala_keluarga,
  pasangan,
  sector_id,
  status,
  notes
)
select
  incoming_families.no_kk,
  incoming_families.nama_kepala_keluarga,
  incoming_families.pasangan,
  sectors.id,
  incoming_families.status,
  'Imported from Excel Database sheet.'
from incoming_families
left join public.sectors on sectors.name = incoming_families.sector_name
on conflict (no_kk) do update
set nama_kepala_keluarga = excluded.nama_kepala_keluarga,
    pasangan = excluded.pasangan,
    sector_id = excluded.sector_id,
    status = excluded.status,
    notes = excluded.notes,
    updated_at = now();

with incoming_individuals(
  family_no_kk,
  no_induk,
  full_name,
  nick_name,
  gender,
  birth_place,
  birth_date,
  blood_type,
  occupation,
  family_relationship,
  phone,
  marital_status,
  baptism_status,
  sidi_status,
  member_status,
  notes
) as (
  values
    ('TGR001', 'TGR001', 'Alfa Nituju Ekadiputra Hia', 'A. Jourel Hia', 'Laki-laki', 'Jakarta', '1992-10-08', null, null, 'Suami', '085718689926', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR001', 'TGR001.1', 'Yemima Daeli', null, 'Perempuan', 'Onolimbu', '1995-08-20', null, null, 'Istri', '085287454642', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR001', 'TGR001.2', 'Jourel Alman Sopandu Hia', null, 'Laki-laki', 'Tangerang Selatan', '2020-02-12', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR001', 'TGR001.3', 'Javlon Alman Sowua Hia', null, 'Laki-laki', 'Tangerang Selatan', '2023-06-12', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR002', 'TGR002', 'Salema Daeli', 'Ina Alfa Hia', 'Perempuan', 'Nias', '1960-12-02', null, null, 'Istri', null, 'Janda', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR003', 'TGR003', 'Hadali Daeli', 'A. Tomo Daeli', 'Laki-laki', 'Nias', '1967-11-01', null, null, 'Suami', '085217930068', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR003', 'TGR003.1', 'Fatiria Daeli', null, 'Perempuan', 'Nias', '1971-10-02', null, null, 'Istri', '085179889744', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR003', 'TGR003.2', 'Sotomo Daeli', null, 'Laki-laki', 'Tangerang', '1997-05-20', null, null, 'Anak', '081286081834', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR003', 'TGR003.3', 'Dewi Hosiani Daeli', null, 'Perempuan', 'Tangerang', '2001-08-14', null, null, 'Anak', '082165896880', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR003', 'TGR003.4', 'Cahyani Tristiani Daeli', null, 'Perempuan', 'Tangerang', '2008-10-24', null, null, 'Anak', '081284123572', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR004', 'TGR004', 'Yosia Halawa', 'A. Lia Halawa', 'Laki-laki', 'Nias', '1964-08-05', null, null, 'Suami', '081287069565', 'Duda', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR005', 'TGR005', 'Estomi Laia', 'A. Felicia Laia', 'Laki-laki', 'Hilisondrekha', '1992-08-18', null, null, 'Suami', '081381784284', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR005', 'TGR005.1', 'Irena Jeska Barasi Gaho', null, 'Perempuan', 'Gunungsitoli', '1993-04-17', null, null, 'Istri', '081323590141', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR005', 'TGR005.2', 'Naureen Mei Nitulo Laia', null, 'Perempuan', 'Nias', '2022-05-31', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR005', 'TGR005.3', 'Jayden Elnathan Ozni Laia', null, 'Laki-laki', 'Tangerang Selatan', '2023-06-21', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR005', 'TGR005.4', 'Rismawati Laia', null, 'Perempuan', 'Hilisondrekha', '2004-06-05', null, null, 'Saudara', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR005', 'TGR005.5', 'Afdal Laia', null, 'Laki-laki', 'Hilisondrekha', '2006-10-09', null, null, 'Saudara', '082283828364', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR005', 'TGR005.6', 'Martin Luther Laia', null, 'Laki-laki', 'Hilisondrekha', '1998-02-27', null, null, 'Saudara', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR005', 'TGR005.7', 'Sastawati Putri Laia', null, 'Perempuan', 'Hilisondrekha', '2006-03-20', null, null, 'Ponakan', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR005', 'TGR005.8', 'Nefisi Gaurifa', null, 'Laki-laki', 'Hilifalago', '2001-08-14', null, null, 'Ponakan', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR006', 'TGR006', 'Sumardin Hura', null, 'Laki-laki', 'Hilibadalu', '1992-09-10', null, null, 'Suami', '082174584453', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR006', 'TGR006.1', 'Tutry Agus Delina Zega', null, 'Perempuan', 'Togilauri', '1995-08-23', null, null, 'Istri', '081317294783', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR006', 'TGR006.2', 'Krismurni Zega', null, 'Perempuan', 'Togilauri', '2001-10-29', null, null, 'Saudara', '082289848199', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR006', 'TGR006.3', 'April Putraman Hura', null, 'Laki-laki', 'Hilibadalu', '2007-04-22', null, null, 'Keponakan', '085319163783', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR007', 'TGR007', 'Arifman Jaya Hura', 'A. Cia Hura', 'Laki-laki', 'Hilibadalu', '1997-08-16', null, null, 'Suami', '081264011171', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR007', 'TGR007.1', 'Ike Trajelita Nurjana Harefa', null, 'Perempuan', 'Lolofaoso', '1998-05-16', null, null, 'Istri', '082176157212', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR007', 'TGR007.2', 'Valencia Manuella Hura', null, 'Perempuan', 'Tangerang Selatan', '2025-06-28', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR007', 'TGR007.3', 'Fatima Waruwu', null, 'Perempuan', 'Onozitoli', '1967-09-17', null, null, 'Ibu', '082124985586', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR007', 'TGR007.4', 'Jeni Mardiana Novritasari Harefa', null, 'Perempuan', 'Lolofaoso', '2000-01-19', null, null, 'Saudara', '082275291335', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR008', 'TGR008', 'Tomi Laia', 'A. Leon Laia', 'Laki-laki', 'Hilisondrekha', '1994-12-19', null, null, 'Suami', '081288222351', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR008', 'TGR008.1', 'Lies Susanti Duha', null, 'Perempuan', 'Hilisataro', '2001-07-26', null, null, 'Istri', '085275534472', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR008', 'TGR008.2', 'Leonathan Titus Laia', null, 'Laki-laki', 'Tangerang Selatan', '2022-02-18', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR008', 'TGR008.3', 'Serani Duha', null, 'Perempuan', 'Hilisondrekha', '1972-07-09', null, null, 'Ibu', null, 'Janda', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR009', 'TGR009', 'Yohan Sosana Harefa', 'A. Daniel Harefa', 'Laki-laki', 'Awa''ai', '1991-07-10', null, null, 'Suami', '081269669212', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR009', 'TGR009.1', 'Herlina', null, 'Perempuan', 'Bosokan', '1997-08-25', null, null, 'Istri', '0853-19320262', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR009', 'TGR009.2', 'Daniel Harefa', null, 'Laki-laki', 'Tangerang Selatan', '2021-12-08', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR010', 'TGR010', 'Asaziduhu Ndruru', 'A. Novi Nduru', 'Laki-laki', 'Nias', '1965-05-07', null, null, 'Suami', '081317840430', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR010', 'TGR010.1', 'Herlina', null, 'Perempuan', 'Bukit Tinggi', '1968-11-02', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR010', 'TGR010.2', 'Jessica Ndruru', null, 'Perempuan', 'Tangerang', '2000-03-07', null, null, 'Anak', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR010', 'TGR010.3', 'Sertika Ndruru', null, 'Perempuan', 'Tangerang', '2002-09-21', null, null, 'Anak', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR011', 'TGR011', 'Agustinus Halawa', 'A. Christine Halawa', 'Laki-laki', 'Simanere', '1995-08-17', null, null, 'Suami', '081219274468', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR011', 'TGR011.1', 'Metilia Tafonao', null, 'Perempuan', 'Nias Selatan', '1996-03-21', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR011', 'TGR011.2', 'Christine Halawa', null, 'Perempuan', 'Jakarta', '2020-04-26', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR011', 'TGR011.3', 'Irene Cahyani Halawa', null, 'Perempuan', 'Tangerang Selatan', '2022-07-01', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR011', 'TGR011.4', 'Gricelda Halawa', null, 'Perempuan', 'Tangerang Selatan', '2023-07-21', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR012', 'TGR012', 'Deali Halawa', null, 'Laki-laki', 'Simanaere', '1997-12-14', null, null, 'Suami', '081313138934', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR012', 'TGR012.1', 'Elly Dwi Utami', null, 'Perempuan', 'Gunung Kidul', '1999-07-24', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR013', 'TGR013', 'Kasia Zebua', 'Ina Jesi Gulo', 'Perempuan', 'Mandrehe', '1956-02-06', null, null, 'Istri', '081398708546', 'Janda', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR013', 'TGR013.1', 'Bebalazi Gulo', null, 'Laki-laki', 'Nias', '1996-04-21', null, null, 'Anak', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR013', 'TGR013.2', 'Rezeki Gulo', null, 'Laki-laki', 'Nias', '1999-06-14', null, null, 'Anak', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR013', 'TGR013.3', 'Afrilian Gulo', null, 'Perempuan', 'Pangkalan Lesung', '2006-04-06', null, null, 'Saudara', '085891037522', 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    (null, 'TGR014', 'Angeraigo Buulolo', null, 'Laki-laki', 'Hili Dauli', '1997-11-21', null, null, 'Anak', '085212589821', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR015', 'TGR015', 'Montanus Buulolo', null, 'Laki-laki', 'Gunungsitoli', '1999-02-24', null, null, 'Suami', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR015', 'TGR015.1', 'Wenima Waruwu', null, 'Perempuan', 'Fatodano', '2002-04-12', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR015', 'TGR015.2', 'Noel Gamaliel Buulolo', null, 'Laki-laki', 'Kampung Dada', '2023-12-14', null, null, 'Anak', null, 'Belum', 'Belum', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR016', 'TGR016', 'Kecitaan Harefa', 'A. Chika Harefa', 'Laki-laki', 'Hiligeo Afia', '1991-04-21', null, null, 'Suami', '081370365956', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR016', 'TGR016.1', 'Kariani Harefa', null, 'Perempuan', 'Lolofaoso', '1994-09-15', null, null, 'Istri', '082282147580', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR016', 'TGR016.2', 'Chika Anecca Harefa', null, 'Perempuan', 'Tangerang Selatan', '2019-04-02', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR016', 'TGR016.3', 'Cathleen Ella Harefa', null, 'Perempuan', 'Depok', '2021-01-11', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR016', 'TGR016.4', 'Indah Ceria Zalukhu', null, 'Perempuan', 'Dahadano', '2004-12-01', null, null, 'Ponakan', '085217929754', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR016', 'TGR016.5', 'Indah Parman Zalukhu', null, 'Laki-laki', 'Dahadano', '2006-09-30', null, null, 'Ponakan', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR016', 'TGR016.6', 'Renungan Harefa', null, 'Laki-laki', 'Hiligeo Afia', '2003-06-15', null, null, 'Ponakan', '081213915394', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR016', 'TGR016.7', 'Aprini Nazara', null, 'Perempuan', 'Lawira 1', '2004-04-14', null, null, 'Ponakan', '082258178048', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR017', 'TGR017', 'Arojasa Harefa', null, 'Laki-laki', 'Hiligeo Afia', '2003-07-03', null, null, 'Anak', '082276810284', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR017', 'TGR017.1', 'Junia Harefa', null, 'Perempuan', 'Hiligeo Afia', '2005-06-16', null, null, 'Anak', '085262896547', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR018', 'TGR018', 'Viktor Zalukhu', null, 'Laki-laki', 'Sawo', '1996-07-09', null, null, 'Anak', '08568657842', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR019', 'TGR019', 'Adrianus Mendrofa', 'A. Velsa Mendrofa', 'Laki-laki', 'Lolofaoso lalai', '1980-02-08', null, null, 'Suami', '081387639997', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR019', 'TGR019.1', 'Niat Mawati Fakho', null, 'Perempuan', 'Hilimbana', '1985-04-29', null, null, 'Istri', '085210257759', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR019', 'TGR019.2', 'Caritas Velesia Solomasi Mendrofa', null, 'Perempuan', 'Tangerang Selatan', '2014-07-27', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR019', 'TGR019.3', 'Jerard Meyer Harazaki Mendrofa', null, 'Laki-laki', 'Tangerang Selatan', '2018-01-04', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR020', 'TGR020', 'Agustinus Ndruru', 'A. Fajar Nduru', 'Laki-laki', 'Jakarta', '1967-11-21', null, null, 'Suami', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR020', 'TGR020.1', 'T Nurmawati Mendrofa', null, 'Perempuan', 'Sibolangit', '1964-10-03', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR021', 'TGR021', 'Sisudin Waruwu', 'A. Dini Waruwu', 'Laki-laki', 'Nias', '1966-12-26', null, null, 'Suami', '082123182883', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR021', 'TGR021.1', 'Sri Kurnia', null, 'Perempuan', 'Jakarta', '1970-06-21', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR022', 'TGR022', 'Beniyami Gea', 'A. Vania Gea', 'Laki-laki', 'Hilinaa', '1984-04-05', null, null, 'Suami', '081316123484', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR022', 'TGR022.1', 'Eva Sandra Indah Hia', null, 'Perempuan', 'Jakarta', '1994-02-09', null, null, 'Istri', '081564789019', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR022', 'TGR022.2', 'Josephine Vania Gea', null, 'Perempuan', 'Tangerang Selatan', '2015-12-12', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR022', 'TGR022.3', 'Jemima Soya Nibenia Gea', null, 'Perempuan', 'Tangerang Selatan', '2018-03-12', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR023', 'TGR023', 'Alinur Zebua', 'A. Juan Zebua', 'Laki-laki', 'Tumori', '1964-08-14', null, null, 'Suami', '081398924171', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR023', 'TGR023.1', 'Tiena Daeli', null, 'Perempuan', 'Nias', '1966-04-24', null, null, 'Istri', '082240266912', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR023', 'TGR023.2', 'Jevon Edric Zebua', null, 'Laki-laki', 'Jakarta', '1994-09-08', null, null, 'Anak', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR024', 'TGR024', 'Juan Edra Agung Zebua', null, 'Laki-laki', 'Jakarta', '1992-04-17', null, null, 'Suami', '081295737200', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR024', 'TGR024.1', 'Novita Sari Zandroto', null, 'Laki-laki', 'Hiliweto Gido', '1999-01-06', null, null, 'Istri', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR024', 'TGR024.2', 'Josluis Fernando Zandroto', null, 'Perempuan', 'Hiliweto Gido', '2001-07-20', null, null, 'Saudara', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR025', 'TGR025', 'Bahagia Halawa', 'A. Hillary Halawa', 'Laki-laki', 'Hilisondrekha', '1993-04-27', null, null, 'Suami', '085360495339', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR025', 'TGR025.1', 'Rosliani Buulolo', null, 'Perempuan', 'Hilisimaetano', '1998-07-06', null, null, 'Istri', '081287203407', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR025', 'TGR025.2', 'Hillary Giana Halawa', null, 'Perempuan', 'Tangerang Selatan', '2025-01-07', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR026', 'TGR026', 'Remis Putra Tafonao', null, 'Laki-laki', 'Doli Doli', '1999-09-30', null, null, 'Anak', '081361178992', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR027', 'TGR027', 'Desman Berkati Larosa', 'A. Grace Larosa', 'Laki-laki', 'Nias', '1987-12-18', null, null, 'Suami', '0852-38147690', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR027', 'TGR027.1', 'Sumiaty Aiba', null, 'Perempuan', 'Salibabu', '1987-10-09', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR027', 'TGR027.2', 'Grace Elyezer Putri Larosa', null, 'Perempuan', 'Tangerang', '2020-10-14', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR028', 'TGR028', 'Simei Waruwu', 'A. Vincent Waruwu', 'Laki-laki', 'Nias', '1966-05-02', null, null, 'Suami', '087780586561', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR028', 'TGR028.1', 'Yaniwati Telaumbanua', null, 'Perempuan', 'Nias', '1970-05-05', null, null, 'Istri', '081803555556', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR028', 'TGR028.2', 'Vincent Waruwu', null, 'Laki-laki', 'Jakarta', '1997-12-12', null, null, 'Anak', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR028', 'TGR028.3', 'Victor Lovenzky Waruwu', null, 'Laki-laki', 'Jakarta', '2004-07-28', null, null, 'Anak', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR028', 'TGR028.4', 'Viddelcatriell Motaro Waruwu', null, 'Laki-laki', 'Jakarta', '2010-10-28', null, null, 'Anak', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR029', 'TGR029', 'Iman Wahyudi Zega', 'A. Gwen Zega', 'Laki-laki', 'Dahadano', '1995-05-13', null, null, 'Suami', '082276232702', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR029', 'TGR029.1', 'Jeni Muliani Gea', null, 'Perempuan', 'Hilimbowo', '1995-11-24', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR029', 'TGR029.2', 'Gwen Cristine Carolin Zega', null, 'Perempuan', 'Tangerang Selatan', '2023-08-26', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR029', 'TGR029.3', 'Brian Carolus Zega', null, 'Laki-laki', 'Tangerang Selatan', '2024-09-29', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR029', 'TGR029.4', 'Deavani Bellicya Zega', null, 'Perempuan', 'Tangerang Selatan', '2025-09-25', null, null, 'Anak', null, 'Belum', 'Belum', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR030', 'TGR030', 'Rahmat Jeni Putra Hia', 'A. Michelle Hia', 'Laki-laki', 'Sisobambowo', '2000-06-19', null, null, 'Suami', '085147112437', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR030', 'TGR030.1', 'Mitra Fianti Daeli', null, 'Perempuan', 'Awa''ai', '2004-03-10', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR030', 'TGR030.2', 'Michelle Elmira Hia', null, 'Perempuan', 'Tangerang Selatan', '2025-10-30', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR030', 'TGR030.3', 'Pintau Jul Pilih Niet Hia', null, 'Perempuan', 'Sisobambowo', '2004-07-04', null, null, 'Saudara', '082251757332', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Anugerah'),
    ('TGR031', 'TGR031', 'Aperius Zai', 'A. Avis Zai', 'Laki-laki', 'Balodano', '1992-04-28', null, null, 'Suami', '081282584994', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR031', 'TGR031.1', 'Etilia Gulo', null, 'Perempuan', 'Lakhene', '1991-10-15', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR031', 'TGR031.2', 'Avisha Berthalois Zai', null, 'Laki-laki', 'Bogor', '2019-09-17', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR031', 'TGR031.3', 'Cicilia Velora Zai', null, 'Perempuan', 'Pamulang', '2022-02-28', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR032', 'TGR032', 'Tema Putra Telaumbanua', null, 'Laki-laki', 'Orahili', '2001-11-19', null, null, 'Anak', '081370477292', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR033', 'TGR033', 'Meylvan Putri Jelita Gulo', null, 'Perempuan', 'Lolofaoso', '2006-05-06', null, null, 'Anak', '082211233531', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR034', 'TGR034', 'Yustinus Hura', null, 'Laki-laki', 'Hilibadalu', '1991-01-02', null, null, 'Anak', '087772719168', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR035', 'TGR035', 'Hendrika Frans Telaumbanua', null, 'Laki-laki', 'Sogae''adu', '2001-04-12', null, null, 'Anak', '085778865612', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR036', 'TGR036', 'Mareti Waruwu', 'A. Michaela Waruwu', 'Laki-laki', 'Sitoluewali', '1994-03-26', null, null, 'Suami', '08111694446', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR036', 'TGR036.1', 'Agustina Ovilia Putri', null, 'Perempuan', 'Gunung Kidul', '1994-08-22', null, null, 'Istri', '081901212226', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR036', 'TGR036.2', 'Michaela Putri Waruwu', null, 'Perempuan', 'Tangerang Selatan', '2022-09-21', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR037', 'TGR037', 'Julisman Gea', 'A. Lovly Gea', 'Laki-laki', 'Gunungsitoli', '1989-06-15', null, null, 'Suami', '085715996542', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR037', 'TGR037.1', 'Ernayanti Telaumbanua', null, 'Perempuan', 'Onozitoli', '1993-05-02', null, null, 'Istri', '085717595558', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR037', 'TGR037.2', 'Charles Erlando Sohahau Gea', null, 'Laki-laki', 'Tangerang Selatan', '2020-11-16', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR037', 'TGR037.3', 'Chansen Dwi Erlan Howu-Howu Gea', null, 'Laki-laki', 'Tangerang Selatan', '2023-10-10', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR038', 'TGR038', 'Viktor Iman Jaya Laowo', 'A. Wanis Laowo', 'Laki-laki', 'Somi', '1992-11-24', null, null, 'Suami', '081318927371', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR038', 'TGR038.1', 'Milika Daeli', null, 'Perempuan', 'Nias', '1983-05-06', null, null, 'Istri', '085310866664', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR038', 'TGR038.2', 'Virginia Nurwanis Laowo', null, 'Perempuan', 'Bangka Tengah', '2013-03-18', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR039', 'TGR039', 'Samelia Waruwu', 'I. Esti Daeli', 'Perempuan', 'Gunungsitoli', '1974-12-16', null, null, 'Istri', '082311598905', 'Janda', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Eben-Haezer'),
    ('TGR039', 'TGR039.1', 'Esti Satriani Daeli', null, 'Perempuan', 'Medan', '2000-05-24', null, null, 'Anak', '085934375828', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Eben-Haezer'),
    ('TGR040', 'TGR040', 'Gregorius Firdaus Riski Gulo', 'A. Lenta Gulo', 'Laki-laki', 'Sisarahili', '1996-12-10', null, null, 'Suami', '085213311930', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR040', 'TGR040.1', 'Meriani Gulo', null, 'Perempuan', 'Simaeasi', '1998-05-13', null, null, 'Istri', '085211038490', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR040', 'TGR040.2', 'Alenta Desniar Gulo', null, 'Perempuan', 'Tangerang', '2018-12-19', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR040', 'TGR040.3', 'Astryd Devina Gulo', null, 'Perempuan', 'Tangerang Selatan', '2021-08-31', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR040', 'TGR040.4', 'Altezza Sanjaya Gulo', null, 'Laki-laki', 'Tangerang Selatan', '2022-11-22', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR040', 'TGR040.5', 'Fatiziduhu Gulo', null, 'Laki-laki', 'Simae''asi', '2002-08-05', null, null, 'Saudara', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR041', 'TGR041', 'Oktafpianus Gea', 'A. Wikel Gea', 'Laki-laki', 'Sindrondro', '1984-10-27', null, null, 'Suami', '081321266825', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR041', 'TGR041.1', 'Satima Daeli', null, 'Perempuan', 'Nias', '1981-04-11', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR041', 'TGR041.2', 'Wikel Alfandi Gea', null, 'Laki-laki', 'Tangerang Selatan', '2011-04-16', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR041', 'TGR041.3', 'Twoandra Perdana Gea', null, 'Laki-laki', 'Tangerang Selatan', '2014-05-02', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR041', 'TGR041.4', 'Twoandri Perdana Gea', null, 'Laki-laki', 'Tangerang Selatan', '2014-05-02', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR041', 'TGR041.5', 'Feberlin Hartayanti Gea', null, 'Perempuan', 'Sindrondro', '1995-02-18', null, null, 'Saudara', '082258178006', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR042', 'TGR042', 'Serianus Waruwu', null, 'Laki-laki', 'Sitoluewali', '1992-09-10', null, null, 'Anak', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR042', 'TGR042.1', 'Seridepi Giawa', null, 'Perempuan', 'Batang Toru', '1997-02-20', null, null, 'Saudara', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR043', 'TGR043', 'Purnama Larosa', 'A. Alden Larosa', 'Laki-laki', 'Binaka', '1992-10-25', null, null, 'Suami', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR043', 'TGR043.1', 'Tiurlina Telaumbanua', null, 'Perempuan', 'Onozitoli', '1994-04-19', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR043', 'TGR043.2', 'Alden Jhonatan Larosa', null, 'Laki-laki', 'Nias', '2022-09-22', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR044', 'TGR044', 'Linus Levis Gulo', 'A. Ezra Gulo', 'Laki-laki', 'Sisarahili', '1995-07-19', null, null, 'Suami', '081285410952', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR044', 'TGR044.1', 'Sumiati Tafonao', null, 'Perempuan', 'Doli Doli', '1995-08-01', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR044', 'TGR044.2', 'Ezra Gevariel Gulo', null, 'Perempuan', 'Depok', '2022-10-19', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR045', 'TGR045', 'Arius Harefa', 'A. Gita Harefa', 'Laki-laki', 'Nias', '1982-10-29', null, null, 'Suami', '081381959424', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR045', 'TGR045.1', 'Nani', null, 'Perempuan', 'Tangerang', '1985-04-27', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR045', 'TGR045.2', 'Gita Christiani Harefa', null, 'Perempuan', 'Tangerang Selatan', '2011-02-10', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR045', 'TGR045.3', 'Gavin Arfan Harefa', null, 'Laki-laki', 'Tangerang', '2019-05-05', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Nazaret'),
    ('TGR046', 'TGR046', 'Fransiskus Ferdiniato Gulo', null, 'Laki-laki', 'Sisarahili', '2003-09-28', null, null, 'Suami', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR046', 'TGR046.1', 'Jernih Putri Harefa', null, 'Perempuan', 'Namohalu', '2001-05-12', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR047', 'TGR047', 'Juliman Agus Ndruru', 'A. Olsen Ndruru', 'Laki-laki', 'Hiligambukha', '1994-09-27', null, null, 'Suami', '081316956833', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR047', 'TGR047.1', 'Aleksi Lilis Arlina Gulo', null, 'Perempuan', 'Sisarahili', '2000-02-17', null, null, 'Istri', '081284317749', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR047', 'TGR047.2', 'Olsen Syahputra Ndruru', null, 'Laki-laki', 'Jakarta', '2022-10-12', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR047', 'TGR047.3', 'Oskar Ananda Putra Ndruru', null, 'Laki-laki', 'Tangerang Selatan', '2025-10-17', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR048', 'TGR048', 'Yusman Gumanõ', 'A. Kris Gumano', 'Laki-laki', 'Nias', '1960-09-11', null, null, 'Suami', '083894449991', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR048', 'TGR048.1', 'Satilia La''ia', null, 'Perempuan', 'Nias', '1963-09-25', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR048', 'TGR048.2', 'Christ Nugroho Gumanõ', null, 'Laki-laki', 'Jakarta', '1990-12-01', null, null, 'Anak', '085781162110', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR049', 'TGR049', 'Fazokhi Waruwu', 'A. Stiven Waruwu', 'Laki-laki', 'Lasara Baene', '1978-06-19', null, null, 'Suami', '085771111668', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR050', 'TGR050', 'Temi Candra', null, 'Laki-laki', 'Jakarta', '1993-03-26', null, null, 'Anak', '0895414821010', 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR051', 'TGR051', 'March Dalta Jonathan Halawa', null, 'Laki-laki', 'Hilizoliga', '2005-03-15', null, null, 'Anak', '085262160539', 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret'),
    ('TGR052', 'TGR052', 'Yupiter Daeli', 'A. Kairos Daeli', 'Laki-laki', 'Onolimbu', '1990-12-24', null, null, 'Suami', '081324969190', 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR052', 'TGR052.1', 'Eltariat Sihura', null, 'Perempuan', 'Bawomataluo', '1994-12-17', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR052', 'TGR052.2', 'Kairos Azokhi Joelly Daely', null, 'Laki-laki', 'Bandung Barat', '2020-07-17', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR052', 'TGR052.3', 'Ivance Sitaro Sohaga Daeli', null, 'Laki-laki', 'Bekasi', '2022-08-15', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR053', 'TGR053', 'Sonasa Zendrato', null, 'Laki-laki', 'Sihare''o', '2005-01-20', null, null, 'Anak', null, 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Anugerah'),
    ('TGR054', 'TGR054', 'Desman Larosa', 'A. Seren Larosa', 'Laki-laki', 'Binaka', '1998-12-18', null, null, 'Suami', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR054', 'TGR054.1', 'Wenisia Gea', null, 'Perempuan', 'Siwalubanua II', '1999-04-14', null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR054', 'TGR054.2', 'Seren Amora Larosa', null, 'Perempuan', 'Tangerang Selatan', '2025-09-22', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR055', 'TGR055', 'Noferius Telaumbanua', 'A. Michelle Talaumbanua', 'Laki-laki', null, null, null, null, 'Suami', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Betlehem'),
    ('TGR055', 'TGR055.1', 'Wahyufin Laia', null, 'Perempuan', null, null, null, null, 'Istri', null, 'Menikah', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR055', 'TGR055.2', 'Michelle Angelista Taluambanua', null, 'Perempuan', 'Balaraja', '2023-09-23', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR055', 'TGR055.3', 'Mikha Angelista Taluambanua', null, 'Perempuan', 'Balaraja', '2023-09-23', null, null, 'Anak', null, 'Belum', 'Sudah', 'Belum', 'Aktif', 'Imported from Excel Database sheet. Status KK: Anggota; Sektor: Betlehem'),
    ('TGR056', 'TGR056', 'Salman Rion Giawa', null, 'Laki-laki', 'Hilizoliga', '2004-04-17', null, null, 'Anak', '085813127668', 'Belum', 'Sudah', 'Sudah', 'Aktif', 'Imported from Excel Database sheet. Status KK: KK; Sektor: Nazaret')
)
insert into public.individuals (
  family_id,
  no_induk,
  full_name,
  nick_name,
  gender,
  birth_place,
  birth_date,
  blood_type,
  occupation,
  family_relationship,
  phone,
  marital_status,
  baptism_status,
  sidi_status,
  member_status,
  notes
)
select
  families.id,
  incoming_individuals.no_induk,
  incoming_individuals.full_name,
  incoming_individuals.nick_name,
  case
    when lower(trim(incoming_individuals.gender)) = 'perempuan' then 'Perempuan'
    else 'Laki-laki'
  end,
  incoming_individuals.birth_place,
  incoming_individuals.birth_date::date,
  incoming_individuals.blood_type,
  incoming_individuals.occupation,
  incoming_individuals.family_relationship,
  incoming_individuals.phone,
  case
    when lower(trim(incoming_individuals.marital_status)) = 'menikah' then 'Menikah'
    when lower(trim(incoming_individuals.marital_status)) = 'duda' then 'Duda'
    when lower(trim(incoming_individuals.marital_status)) = 'janda' then 'Janda'
    else 'Belum'
  end,
  case
    when lower(trim(incoming_individuals.baptism_status)) = 'sudah' then 'Sudah'
    else 'Belum'
  end,
  case
    when lower(trim(incoming_individuals.sidi_status)) = 'sudah' then 'Sudah'
    else 'Belum'
  end,
  case
    when lower(trim(incoming_individuals.member_status)) = 'meninggal' then 'Meninggal'
    when lower(trim(incoming_individuals.member_status)) = 'nonaktif' then 'Nonaktif'
    else 'Aktif'
  end,
  incoming_individuals.notes
from incoming_individuals
left join public.families on families.no_kk = incoming_individuals.family_no_kk
on conflict (no_induk) do update
set family_id = excluded.family_id,
    full_name = excluded.full_name,
    nick_name = excluded.nick_name,
    gender = excluded.gender,
    birth_place = excluded.birth_place,
    birth_date = excluded.birth_date,
    blood_type = excluded.blood_type,
    occupation = excluded.occupation,
    family_relationship = excluded.family_relationship,
    phone = excluded.phone,
    marital_status = excluded.marital_status,
    baptism_status = excluded.baptism_status,
    sidi_status = excluded.sidi_status,
    member_status = excluded.member_status,
    notes = excluded.notes,
    updated_at = now();

commit;

-- Quick checks after running:
-- select count(*) as families from public.families;
-- select count(*) as individuals from public.individuals;
-- select count(*) as independent_individuals from public.individuals where family_id is null;
-- select s.name, count(f.id) from public.sectors s left join public.families f on f.sector_id = s.id group by s.name order by s.name;
